FROM python:3.11-slim

WORKDIR /app
#ENV PYTHONPATH=/app/..
# Kopiere alle notwendigen Dateien
COPY . /app
COPY ./map

# Installiere die Dependencies
RUN pip install --no-cache-dir requests

# Exporter starten
CMD ["python", "exporter.py"]