version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  exporter:
    build: ./exporter
    ports:
      - "8000:8000"
    volumes:
      - ./exporter:/app  # Falls du dort auch live entwickeln willst

  python-container:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app  # ← Live-Mount vom Host in den Container
    working_dir: /app
    command: ["python", "app.py"]  # Kein fixer Pfad, da wir im /app arbeiten
    #ports:
     # - "5001:5000"  # Optional, falls deine App Flask o. ä. ist
    environment:
      - PYTHONUNBUFFERED=1