version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  exporter:
    build: ./exporter
    ports:
      - "8000:8000"
    volumes:
      - ./exporter:/app  # Falls du dort auch live entwickeln willst

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5001:5000"
    environment:
      - PYTHONUNBUFFERED=1