
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir requests
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "/app/app.py"]  # Die Python-Datei wird hier ausgeführt